---
env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  jest: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
  sourceType: module
settings:
  react:
    version: latest
plugins:
  - react
  - react-hooks
  - prettier
  - '@typescript-eslint'
extends:
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  prettier/prettier: error
